name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to Remote Server (EC22)
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_HOST }} "
            cd /home/ubuntu/Api 
            git pull origin main
            mvn clean package -DskipTests
            ./executar.sh"

