name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to Remote Server (EC22)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no private_key ${{ secrets.SERVER_HOST }} "
              cd /home/ubuntu/Api 
              git pull origin main
              mvn clean package -DskipTests
              ./executar.sh"
